#Author: Giovanni Bussotti
#This script is part of the project "strategies4mappingLncRNAs" and it can be used to analyze multiple read_statistics.pl outputs (es: the ones for AB-BlastR, AB-BlastNopt, AB-BlantN)
#This script compares the number of transcript that a certain method managed to find (N) with the Z-Score of the distribution generated by read_statistics.pl (Z)
#The Z score refers to the average RPKM of the detected transcripts over a randomization of random transcript projections.
#This script will return:
#1- a plot having N on the x-axis and Z on the y-axis
#2- a density plot (which is like an histogram interpolation) for each experiment with the real average RPKM maked by a green bar
#3- all the numbers in the standard output, including the pearson normality test (beacuse the z-score comparison really make sense if the distributions are normal) 
#usage:
#cat RPKManalysis_NZgraph_and_histograms.R | R --slave --args type nameFile readStatisticsExperiment1 readStatisticsExperiment2 ..
#type = [transcript|exon] Choose to consider either exons either transcripts. The N will be either the number of mapped transcript or the number of mapped exons. The Z-score will be choosen accordingly (from the distribution of exons or the distribution of transcripts)
#nameFile = Just a file listing the names to use in the legend. The names must have the same order of the experiments whose are referring to (es: AB-BlastR,AB-BlastNopt,AB-BlastN)
#readStatisticsExperimentXX = read_statistics.pl experiment folder.  
###example commandLine: cat RPKManalysis_NZgraph_and_histograms.R | R --slave --args transcript names ../experiments/exp_1/qualityCheck/reads_statistics/grapeMergedAndSortedSamtools/ ../../abblastnOpt/experiments/exp_1/qualityCheck/reads_statistics/grapeMergedAndSortedSamtools/ ../../abblastn/experiments/exp_1/qualityCheck/reads_statistics/grapeMergedAndSortedSamtools/


##########################

Args <- commandArgs();                #Args[4] will contain the first parameter


type=Args[4]
namesFile = (Args[5])
usedNames=read.table(namesFile,as.is=TRUE)
usedNames=as.vector(usedNames[,1])
library(nortest)	
library(RColorBrewer)
usedCol=c()
Ns=c()
Zs=c()
counter=0
mypalette<-brewer.pal(9, name = "Set1")

for ( i in 6:length(Args) ) {
	experiment = Args[i]
	print (experiment)
	counter=counter+1
	currentName=usedNames[counter]
        currentCol=mypalette[counter]
        usedCol<-c(usedCol , mypalette[counter])

	#Z-Score
	if (type=="transcript"){
		X=read.table(paste(experiment,"/average.tx.rpkm",sep=""),header=F)
	} else if (type=="exon"){
		X=read.table(paste(experiment,"/average.ex.rpkm",sep=""),header=F)
	} else {
		print("type ERROR!!")
	}
	dim=nrow(X)
	real=X[dim,1]
	lim=dim-1
	Y=X[1:lim,1]
	ntest=pearson.test(Y)$p.value
	zscore=(real-mean(Y))/sd(Y)
	print (paste ("Pearson normality test P-Value:",ntest))
	print (paste ("Z-Score",zscore))


	#histogram
	dY<-density(Y)
	jpeg(filename=paste("histogram_",type,"_",currentName,".jpeg",sep=""))
	plot(dY,main=currentName,col=currentCol,xlim=c(0,real))
	polygon(dY, col=currentCol, border=currentCol)	
	#hist(dat, freq=F, xlim=xlim, ylim=ylim, col="orange",xlab="bin",main=(fileName),breaks=as.numeric(b))
	abline(v=real,col="dark green")  
	dev.off()




	#N
	if (type=="transcript"){
		X=read.table(paste(experiment,"/transcripts.rpkm",sep=""),header=F)
		N=nrow(X)
		print ("N transcripts ")
	} else if (type=="exon"){
		X=read.table(paste(experiment,"/exons.rpkm",sep=""),header=F)
		N=nrow(X)
		print ("N exons ")
	}else {
		print("type ERROR!!")
	}
	print(N)


	Ns=c(Ns,N)
	Zs=c(Zs,zscore)
}



minN=0
maxN=max(Ns)
minZ=min(Zs)
maxZ=max(Zs)
jpeg(filename=paste("out_NandZ_",type,".jpeg",sep=""))
plot(Ns,Zs,xlim=c(minN,maxN),ylim=c(minZ,maxZ),col=usedCol,pch=20,cex=3,type="p" )
legend( "topleft" , usedNames , fill=usedCol)
dev.off()